### ISSUE TITLE
Suppress iPad native keyboard

### ISSUE THREAD

**Issue by pulkitsinghal** [antonio-spinelli/ng-virtual-keyboard#1]
Is it possible to add functionality to suppress the native keyboard when viewing a HTML5 site that uses ng-virtual-keyboard for its text fields and areas?

cc @Chhaya-rai

**Comment by Mottie** [comment]
Have you tried setting the `lockInput` option to `true`? This option basically sets the input to readonly and "should" prevent the native keyboard from opening, but it may not work on iPads (I don't own one so I can't test it) :disappointed:

Alternatively, you could try code that some other users have shared [here](https://github.com/Mottie/Keyboard/issues/161#issuecomment-16876729) or [here](https://github.com/Mottie/Keyboard/issues/334#issuecomment-118410452).
