### ISSUE TITLE
Why is there an typeerror that $(xxx).keyboard(newConfig) is not a function at ng-virtual-keyboard.js?

### ISSUE THREAD

**Issue by fukua777** [antonio-spinelli/ng-virtual-keyboard#10]
TypeError: $(...).keyboard is not a function at ng-virtual-keyboard.js:96:30

**Comment by antonio-spinelli** [comment]
Hi, can you explain in detail when and how this error show up? :)
It is a new fresh project or an old one with this lib already working on that?

**Comment by fukua777** [comment]
It is a new fresh project. I use the directive as your way that importing the ng-virtual-keyboard.js and making the config.But there is a error point to your js. Is it not correct the way importing the files ?
![error](https://user-images.githubusercontent.com/19884392/27817144-3230be64-60c2-11e7-8cd9-b01628b9e22c.png)
![import](https://user-images.githubusercontent.com/19884392/27817179-55ca4994-60c2-11e7-9839-3071b1393b90.png)

**Comment by antonio-spinelli** [comment]
Can you recreate it in [plunker](https://plnkr.co/) or [jsfiddle](https://jsfiddle.net)?
The demo page still working for you? I think you miss something.

**Comment by fukua777** [comment]
Thank you for your reply. The problem has been solved. It probably because of the loading order for angularjs, angularjs plugins and your js.
