### ISSUE TITLE
The value in the input field is not mapped to the ng-model

### ISSUE THREAD

**Issue by JessieAdams** [antonio-spinelli/ng-virtual-keyboard#13]
Hi Mottie,
My issue is that, when i type a word in the input field , the ng-modal is not updated. The input field still shows ng-empty. Any way to fix this?

Thanks in advance.

**Comment by Mottie** [comment]
Hi @JessieAdams!

I'm not proficient with Angular, so I'll have to ask someone else help you with this question.

**Comment by aravindG92** [comment]
@antonio-spinelli can you help in this issue. Even I am facing this issue to map the value to ngModel

**Comment by antonio-spinelli** [comment]
Hi @JessieAdams 
I'm pretty sure that the input is not binded to the model. Can you share an example so I can test it and fix it.

**Comment by JessieAdams** [comment]
Using the **autoUpdateModel: true,** solved my issue.
Found it in the demo config.

```
			$scope.t06Config = {
				layout: 'alpha',
				extensions: {
					addTyping: false,
					addCaret : true
				},
				autoAccept: true,
				usePreview: false,
				autoUpdateModel: true,
				noFocus: true,
            	lockInput: true,
			};
```

Many thanks :)
