### ISSUE TITLE
Caret extension

### ISSUE THREAD

**Issue by jpauldhas** [antonio-spinelli/ng-virtual-keyboard#14]
Hi,
I use the lockInput property to disable the native keyboard which makes the input field readonly. This also removes the cursor from the text area.
But we also want the cursor to be displayed on the field.
In jQuery/mottie keyboard we use the caret extention like this 
```
$('#keyboard')
  .addCaret({
                caretClass : 'blinking-cursor',
    		charAttr   : 'data-character',
    		charIndex  : 1,
    		offsetX    : 0,
    		offsetY    : 20,
    		adjustHt   : 0
})
```

How to use the same by specifying the properties in the controller?
Thanks.

**Comment by antonio-spinelli** [comment]
Hi @CrazYoshi ,
As you can see in demo page and src, just put it under extensions in config.
Example:
```
$scope.vkConfig = {
	layout: 'international',
	autoAccept: true,
	extensions: {
		addScramble: {randomizeOnce: false},
		addTyping: false,
		addCaret: {
			caretClass : 'blinking-cursor',
			charAttr   : 'data-character',
			charIndex  : 1,
			offsetX    : 0,
			offsetY    : 20,
			adjustHt   : 0
		}
	}
};
```

**Comment by jpauldhas** [comment]
@antonio-spinelli ,

Thank you so much for the clarification.
