### ISSUE TITLE
Keyboard destroy on scope destroy issue

### ISSUE THREAD

**Issue by BastienVerschaete** [antonio-spinelli/ng-virtual-keyboard#15]
Following your change that destroys the keyboard when scope is destroyed, an error is sometimes thrown in the console when for some reason the keyboard doesn't exist.

Would it be possible to add an if-statement to check whether or not the keyboard is actually available?
https://github.com/antonio-spinelli/ng-virtual-keyboard/blob/21494c0df10e131e1f98042a2d03e0c1cba77196/dist/ng-virtual-keyboard.js#L137-L139

```javascript
scope.$on('$destroy', function() {
	if($(elements[0]).getkeyboard()) $(elements[0]).getkeyboard().destroy();
});
```

Everytime I change webpages I get the following error thrown in the console: 
```javascript
TypeError: Cannot read property 'destroy' of undefined
    at ng-virtual-keyboard.js:138
    at Scope.$broadcast (angular.js:18005)
    at Scope.$destroy (angular.js:17623)
    at cleanOld (angular-ui-router.js:3978)
    at angular-ui-router.js:3984
    at processQueue (angular.js:16383)
    at angular.js:16399
    at Scope.$eval (angular.js:17682)
    at Scope.$digest (angular.js:17495)
    at angular.js:17721
```

Thanks

**Comment by antonio-spinelli** [comment]
Done. You can find it in release 0.3.2
