### ISSUE TITLE
Small typo in recent release

### ISSUE THREAD

**Issue by BastienVerschaete** [antonio-spinelli/ng-virtual-keyboard#16]
Hello, thank you for the quick response on my latest issue.
The code you wrote works, except you made a typo on line 117:

https://github.com/antonio-spinelli/ng-virtual-keyboard/blob/4c24d655c4b6f39aa54bd208c38bd0ceefb70875/src/ng-virtual-keyboard.js#L117

I'm fairly sure this has to be `var element = elements[0]`.

Thank you for your time and your port!

**Comment by antonio-spinelli** [comment]
My bad, sorry for that!
