### ISSUE TITLE
update config VKI_CONFIG.relative dynamically from angularjs scope function

### ISSUE THREAD

**Issue by naushrambo** [antonio-spinelli/ng-virtual-keyboard#17]
I want to update the VKI_CONFIG.relative value dynamically . like the user have a choice to change the keyboard relative value, and see the change.

**Comment by antonio-spinelli** [comment]
Let me clear the question: you need to change the vk config after the keyboard is binded to the element. Am I right?

**Comment by antonio-spinelli** [comment]
By the way you can try with the new release (0.4.0).

**Comment by naushrambo** [comment]
> Let me clear the question: you need to change the vk config after the keyboard is binded to the element. Am I right?

Exactly, yes
