### ISSUE TITLE
how about use Zh-cn

### ISSUE THREAD

**Issue by zhangtingwz** [antonio-spinelli/ng-virtual-keyboard#18]
excese me
Im a new learner, see the ng-virtual-keyboard, i cant find how to use chinese ,maybe i not find ,please help me,thank you very much

**Comment by zhangtingwz** [comment]
excese me
I`m a new learner, see the ng-virtual-keyboard, i can`t find how to use chinese ,maybe i not find ,please help me,thank you very much

**Comment by antonio-spinelli** [comment]
You can reference to [Mottie/Keyboard](https://github.com/Mottie/Keyboard) documentation about languages and layouts.
https://mottie.github.io/Keyboard/docs/layouts.html
