### ISSUE TITLE
Cannot find module 'ng-virtual-keyboard' in Angular 6

### ISSUE THREAD

**Issue by pinaakimajumder** [antonio-spinelli/ng-virtual-keyboard#19]
Hi @antonio-spinelli,

I am trying to integrate ng-virtual-keyboard in my Angular6 project, but getting '**error TS2307: Cannot find module 'ng-virtual-keyboard'**'

Steps I do -

1. _npm install ng-virtual-keyboard_
2. _npm install --save @types/virtual-keyboard_ (this command mentioned in 'TypeScript' section of 'https://github.com/Mottie/Keyboard')

**package.json -**

`{`
&nbsp;&nbsp;&nbsp;`"dependencies": {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`"@angular/compiler": "^6.1.10",`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`"@angular/core": "^6.1.10",`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`...`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`"@types/virtual-keyboard": "^1.26.1",`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`"ng-virtual-keyboard": "^0.4.0",`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`"rxjs": "~6.6.0",`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`"tslib": "^2.0.0",`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`"zone.js": "^0.8.28"`
&nbsp;&nbsp;&nbsp;`},`
&nbsp;&nbsp;&nbsp;`"devDependencies": {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`"@angular-devkit/build-angular": "^0.12.2",`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`"@angular/cli": "^7.2.2",`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`"@angular/compiler-cli": "^6.1.10",`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`...`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`"ts-node": "~3.2.0",`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`"tslint": "~5.7.0",`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`"typescript": "^2.9.2"`
&nbsp;&nbsp;&nbsp;`}`
`}`

Did I miss anything? Thanks in advance.

![module-error-1](https://user-images.githubusercontent.com/79135437/110158602-98e9cb00-7e0f-11eb-8afe-54e04da966ec.jpg)

**Comment by antonio-spinelli** [comment]
It's an old project for AngularJs (ver 1). It doesn't work with Angular 2+
