### ISSUE TITLE
Changing Language

### ISSUE THREAD

**Issue by jeson114** [antonio-spinelli/ng-virtual-keyboard#4]
How do i change the language of the keyboard ?
Is there  a layout directive ?

**Comment by jeson114** [comment]
ok i changed the language by passing ng-virtual-keyboard="{layout:'hindi'}"
How do i bind the keys to the keyboard?

**Comment by jeson114** [comment]
i need the layout to be mapped to the keyboard

**Comment by antonio-spinelli** [comment]
What do you mean? Your physical keyboard? Are you able to do it with Mottie/Keyboard?

**Comment by antonio-spinelli** [comment]
Take a look at the new version (0.2.0) and let me know if it helped you

**Comment by jeson114** [comment]
yes the physical keyboard ..and yes i ll check the new version

**Comment by jeson114** [comment]
Mottie keyboard has that "Custom: Mapped Keys" feature right . Isn't that the same thing or maybe i am mistaken

**Comment by antonio-spinelli** [comment]
You can use all the config and extension that you can find in Mottie/Keyboard.

**Comment by Mottie** [comment]
I recently added a [`beforeInsert` callback](https://github.com/Mottie/Keyboard/wiki/Methods#beforeinsert) which should make remapping the keyboard much easier!
