### ISSUE TITLE
Help with ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by mdsteenb** [antonio-spinelli/ng-virtual-keyboard#5]
ReferenceError: $ is not defined
    at Object.attach (http://localhost:8000/app/js/ng-virtual-keyboard.js:80:19)

html is
          <input id="t01" type='text' name="myProperty" ng-model="myProperty" ng-virtual-keyboard="myKeyboard" ng-click="onKeyboardClick('t01')" />

and controller.js is

var phonecatApp = angular.module('phonecatApp', ['ng-virtual-keyboard']);

function PhoneListCtrl($scope, $http, ngVirtualKeyboardService) {
    $http.get('phones/phones.json').success(function (data) {  
        $scope.phones = data;
        $scope.phones = data.splice(0, 5);
    });

```
$scope.myKeyboard = {
    layout: 'alpha',
    extensions: {
        addTyping: false
    }
};

$scope.onKeyboardClick = function (id) {
    $scope.myProperty = "made it this far " + id;
    var keyboard = ngVirtualKeyboardService.getKeyboardById(id); 
    if (keyboard) {
        $scope.myProperty = "keyboard is known "+ keyboard.isOpen;

        if (keyboard.isOpen) {
            keyboard.close();
        } else {
            keyboard.reveal();
        }
    }
};
$scope.orderProp = 'age';
```

}
PhoneListCtrl.$inject = ['$scope', '$http', 'ngVirtualKeyboardService'];

phonecatApp.controller('PhoneListCtrl', PhoneListCtrl);

**Comment by antonio-spinelli** [comment]
Can you put the entire code on http://codepen.io/ or something like that? I think you missed some parts.
By the way "$ is not defined" means that jQuery is not defined. Maybe you jumped the jQuery.js import.

**Comment by mdsteenb** [comment]
Antonio - Thank you for the pointer - that is correct. Now I'm struggling
with how to style the keyboard - which css files drive the actual layout of
the keyboard itself - are you using the classes that are in the mottie
keyboard as well?

**Comment by antonio-spinelli** [comment]
You can use the jquery mottie style or a different one like I did in the demo.

**Comment by mdsteenb** [comment]
Sorry for the newbie questions - but I noticed that the style of your
demo's input seems to be coupled to the input style of the keyboard - I'm
trying to keep the <input> tag looking like a normal input tag without
inheriting the style of the keyboard's input - seems when I add the
 ng-virtual-keyboard tag to the input - is when it kicks in - any pointers
on how to decouple it so it leaves the formatting of the input tag alone?

**Comment by antonio-spinelli** [comment]
All you can do with Mottie/Keyboard you can do with ng-virtual-keyboard: it's just a wrapper.
If you can find in the mottie demo or documentation what you are looking for, just copy the config on the ng-virtual-keyboard and it will works!
By the way, if I'm not wrong, what you are looking for is 'usePreview': just set it to 'false'. :)
