### ISSUE TITLE
Keyboard input does not trigger ngChange.

### ISSUE THREAD

**Issue by RoryOSiochain** [antonio-spinelli/ng-virtual-keyboard#6]
Hi,

Thanks for a great wrapper to a great library. 

If typing into a text input field, an ngChange is usually fired per keypress, whereas it is only fired on accept with ng-virtual-keyboard. Is there a way of causing an ngChange event to be fired per keypress?

Thanks,
Rory

**Comment by antonio-spinelli** [comment]
Hi @RoryOSiochain ,

ng-change is fired only when your model change, an event that will occur only when you accept input from virtual-keyboard (like accept).
Try with "change" option in your virtual-keyboard:
`VKI_CONFIG.change: function(e, keyboard, el) {
    console.log("test");
};`
or
`$scope.vkConfig = {
    change: function(e, keyboard, el) {
        console.log("test");
    }
};`

**Comment by RoryOSiochain** [comment]
Thanks for the reply @antonio-spinelli,

Using your suggestion of config.change, but maybe a little differently, I've added the following line under the newConfig.accepted instruction in your service:

`newConfig.accepted = config.accepted || inputCallback; // Existing Line`
`newConfig.change = config.change || inputCallback; // New Line`

This updates the ng-model and fires ng-change as it is typed now.
