### ISSUE TITLE
Is there a way to include this module in angular 2 ?

### ISSUE THREAD

**Issue by debanjana** [antonio-spinelli/ng-virtual-keyboard#9]

**Comment by antonio-spinelli** [comment]
I don't' have any plan on a new version for "angular 2", but I will be probably forced to do that in a few months cause I will migrate some app that use ng-virtual-keyboard.
By the way this wrapper it's pretty easy. I'm sure it's not complicated to create a new one from that.

**Comment by tarlepp** [comment]
@debanjana if you're still looking for angular 2+ solution you could use this one: https://github.com/protacon/ng-virtual-keyboard

**Comment by vkurlyan** [comment]
Probably we can use this answers to include virtual keyboard in angular 2 https://stackoverflow.com/questions/38289304/angular-2-doesnt-update-input-value-modified-by-third-party-libraries

Update: **Here described how to do it:**
https://stackoverflow.com/questions/46929097/cant-use-virtual-keyboard-jquery-plugin-with-angular-4-webpack
